# Generated by Django 4.2 on 2023-05-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('muscle_group', models.CharField(blank=True, null=True)),
                ('body_part', models.CharField(blank=True, null=True)),
                ('equipment', models.CharField(blank=True, null=True)),
                ('gif_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exercises',
                'managed': True,
            },
        ),
    ]
