# Generated by Django 4.2 on 2023-05-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0005_remove_workout_user_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='routine_builder.routine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
