# Generated by Django 4.2 on 2023-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0006_workout_routine_alter_routine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
