# Generated by Django 4.2 on 2023-05-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0007_workout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='routine',
        ),
    ]
