# Generated by Django 4.2 on 2023-05-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0010_rename_exercise_workout_exercise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
