# Generated by Django 4.2 on 2023-05-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0011_rename_exercise_id_workout_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AddField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='routine_builder.routine'),
            preserve_default=False,
        ),
    ]
