# Generated by Django 4.2 on 2023-05-10 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0012_remove_workout_name_workout_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine_builder.routine'),
        ),
    ]
