# Generated by Django 4.2 on 2023-05-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0013_alter_workout_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='notes',
        ),
        migrations.AddField(
            model_name='routine',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished')], default='Started', max_length=8),
        ),
        migrations.AlterField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routine_workouts', to='routine_builder.routine'),
        ),
    ]
