# Generated by Django 4.2 on 2023-05-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0014_remove_routine_notes_routine_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='routine_workouts', to='routine_builder.routine'),
            preserve_default=False,
        ),
    ]
