# Generated by Django 4.2 on 2023-05-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_builder', '0015_alter_workout_routine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='name',
            new_name='routine_name',
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='routine_builder.exercises'),
        ),
    ]
